### ISSUE TITLE
lam:8.6 Does not obey variables set in docker-compose.yml

### ISSUE THREAD

**Issue by sudoshi** [LDAPAccountManager/lam#276]
I must be doing something wrong.  I tried using both a .env with these variables and setting them in the docker-compose.yml itself:

```
version: "3.7"

###ldap-account-manager

services:

  ldap-account-manager:
    image: ghcr.io/ldapaccountmanager/lam:8.6
    container_name: ldap-account-manager
    restart: always
    ports:
      - "8180:80"
    environment:
      - LAM_SKIP_PRECONFIGURE=false
      - LAM_PASSWORD=acumenus
      - LAM_LANG=en_US
      - LDAP_SERVER=ldap://openldap:1389
      - LDAP_DOMAIN=acumenus.net
      - LDAP_BASE_DN=dc=acumenus,dc=net
      - LDAP_USER=cn=admin,dc=acumenus,dc=net
      - LDAP_USERS_DN=ou=users,dc=acumenus,dc=net
      - LDAP_GROUPS_DN=ou=acumenus,dc=acumenus,dc=net
      - DEBUG=true
    networks:
      - traefik-proxy
    command: /bin/sh -c "a2enconf lam-httpd && apache2ctl -DFOREGROUND"
    volumes:
      - 'ldap-account-manager-data:/var/lib/ldap-account-manager/config'
      - './lam/apache/lam-httpd.conf:/etc/apache2/conf-available/lam-httpd.conf
````

But, upon login:

![Screenshot 2023-12-31 at 11 44 38 PM](https://github.com/LDAPAccountManager/lam/assets/100962480/9e5c7908-ef7a-4e57-ab61-483a6c51195c)
![Screenshot 2023-12-31 at 11 44 56 PM](https://github.com/LDAPAccountManager/lam/assets/100962480/7fa9e2fc-c616-4f06-8b41-27f00caaab29)
![Screenshot 2023-12-31 at 11 45 14 PM](https://github.com/LDAPAccountManager/lam/assets/100962480/f6cb3bd7-34fc-469b-97e2-df4b7093061b)

None of the variables are inherited.

Please advise?

Thank you and Happy New Year!

**Comment by gruberroland** [comment]
You do not run start.sh but have "command" set. Looks like the default init script is not run.
See https://github.com/LDAPAccountManager/lam/blob/develop/lam-packaging/docker/docker-compose.yml for reference.

**Comment by sudoshi** [comment]
I apologize, I don't fully understand your suggestion.  I assumed that command argument was only/specifically for apached within the container.  I did not realize it had to do with the start.sh script.  I will remove it and retry.

Also does this matter if I am pulling the image from the registry?

```
  ldap-account-manager:
    build:
      context: .
```

**Comment by sudoshi** [comment]
Success.  Thank you!  That fixed the issue.  I have one more question...

Upon login:

![Screenshot 2024-01-01 at 2 34 19 PM](https://github.com/LDAPAccountManager/lam/assets/100962480/c74119de-9ee8-4f20-ae33-778b2643267b)

I assume I have misconfigured something in openldap and there is no unix group for the users.  Do you know how to rectify that:

```
 openldap:
    image: bitnami/openldap:2.6
    container_name: openldap
    restart: always
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_LOG_LEVEL=512
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=Acumenus321$%
      - LDAP_USERS=user00,user01,user02,acumenus
      - LDAP_PASSWORDS=password0,password1,password2,acumenus
      - LDAP_ROOT=dc=acumenus,dc=net
      - LDAP_ADMIN_DN=cn=admin,dc=acumenus,dc=net
      - LDAP_GROUP=groups
      - LDAP_USER_DC=users
    networks:
      - traefik-proxy
    volumes:
      - 'openldap-data:/bitnami/openldap'

networks:
  traefik-proxy:
    #external: true ### --> Necessary to connect these services to the main Broadsea services stack

volumes:
  ###ldap-account-manager
  lamconfig:
    name: lamconfig
  ###openLDAP
  openldap-data:
    name: openldap-data
```

Thanks again for your help :)
