### ISSUE TITLE
 config.json failed: no such file or directory

### ISSUE THREAD

**Issue by fredericrous** [LDAPAccountManager/lam#95]
I get the following error in docker logs when I run the container

```sh
starting container failed: oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\"/var/lib/ldap-account-manager/config\") set in config.json failed: no such file or directory"
```

Here is a stripped version of my compose configuration

```
  ldapaccountmanager:
    image: ldapaccountmanager/lam:stable
    volumes:
      - ${SHARED_FOLDER}/ldap/lam/etc:/etc/ldap-account-manager
      - ${SHARED_FOLDER}/ldap/lam/var:/var/lib/ldap-account-manager
    environment:
      - LDAP_DOMAIN=mydomain.com
      - LDAP_SERVER=ldap://ldap:389
      - LDAP_USER=cn=admin,dc=mydomain,dc=com
      - LAM_PASSWORD=password
      - LDAP_ORGANISATION=myOrg
      - LDAP_ADMIN_PASSWORD=mypass
```

I can reproduce the same issue if I mount the subfolders config and sess directly 

```
    volumes:
      - ${SHARED_FOLDER}/ldap/lam/etc/:/etc/ldap-account-manager
      - ${SHARED_FOLDER}/ldap/lam/config/:/var/lib/ldap-account-manager/config
      - ${SHARED_FOLDER}/ldap/lam/session/:/var/lib/ldap-account-manager/sess
```

## reprodution workflow:

- spawn the container on docker swarm with the volumes mounted to file system. (choose one of the configs provided above. SHARED_FOLDER can be an environment variable that targets any directory of your choosing)
- with `docker service ps` and `docker service logs` commands, diagnose the file config.cfg must be created

```
sed: can't read /etc/ldap-account-manager/config.cfg: No such file or directory
```

- use `docker  run` and `docker cp` command to get the file from a fresh container that has no volume mounted. Put the file at ${SHARED_FOLDER}/ldap/lam/etc/config.cfg
- diagnose the error from `docker service logs`

```
sed: can't read /var/lib/ldap-account-manager/config/lam.conf: No such file or director
```

- use `docker  run` and `docker cp` command to get the file from a fresh container that has no volume mounted. put the file at ${SHARED_FOLDER}/ldap/lam/config/lam.conf
- run the container again. notice with docker service logs that the container is running.
- try to access the container without success
- check docker logs to notice the error

```sh
starting container failed: oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\"/var/lib/ldap-account-manager/config\") set in config.json failed: no such file or directory"
```

I noticed another user got a similar issue: https://github.com/LDAPAccountManager/lam/issues/83
